FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY main.go go.mod .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/app .
EXPOSE 80

ENTRYPOINT ["/app/app"]